### ISSUE TITLE
您好，我发现有个小问题

### ISSUE THREAD

**Issue by 377376701** [saiwu-bigkoo/Android-QuickSideBar#1]
用户在选择A-Z，单击选择的时候比如选择A其实获取的焦点是C了，这一点有点体验问题

**Comment by qqliu10u** [comment]
QuickSideBarView类 

dispatchTouchEvent 112行：final int newChoose = (int) (y / mHeight \* mLetters.size());
改为 final int newChoose = (int) ((y-mPaddingTop) / mHeight \* mLetters.size());即可。

因为mHeight是减去了paddingTop的，y也必须减去才能在mHeight内挪动

**Comment by saiwu-bigkoo** [comment]
1.0.2已修复
