### ISSUE TITLE
QuickSideBarView问题

### ISSUE THREAD

**Issue by liaodongxiaoxiao** [saiwu-bigkoo/Android-QuickSideBar#4]
1. 我的需求是RecyclerView数据来自服务器，当没有调用adapter 的addAll方法时，QuickSideBarView的A-Z标题会纠结到屏幕的右上角
2. QuickSideBarView的touch好像错位了，点击B，显示出来的是A

**Comment by saiwu-bigkoo** [comment]
1.0.2已修复
