### ISSUE TITLE
点击展示效果体验不好

### ISSUE THREAD

**Issue by gongxiaobing** [saiwu-bigkoo/Android-QuickSideBar#5]
当点击的时候，发现每次都会向下进行偏移一些，导致不能准确的点击自己想要的索引，后发现，是计算索引高度时有点小问题， final int newChoose = (int) (y / mHeight \* mLetters.size());为了让更多的人完美的使用，建议改进。

**Comment by saiwu-bigkoo** [comment]
1.0.2已修复
