### ISSUE TITLE
View的Widget和Height计算错误

### ISSUE THREAD

**Issue by walgr** [saiwu-bigkoo/Android-QuickSideBar#6]
你好，我在使用你的项目过程中发现View显示A...Z错位了  看了源代码是你这里计算错误了。
mHeight = getHeight();
 mWidth = getWidth();
应该是 mHeight = getMeasuredHeight();
            mWidth = getMeasuredWidth();
请验证。

**Comment by saiwu-bigkoo** [comment]
fix
